typedef enum {
	CODE_HALT,
	
	CODE_DATUM_FALSE,
	CODE_DATUM_TRUE,
	CODE_DATUM_NULL,
	CODE_DATUM_SYMBOL,
	CODE_DATUM_CHAR,
	CODE_DATUM_NUMBER,
	CODE_DATUM_STRING,
	
	CODE_ALLOCATE_CLOSURE,
	CODE_CLOSURE_SET,
	
	CODE_VAR_GLO,
	CODE_SET_GLO,
	CODE_VAR_LOC,
	CODE_SET_LOC,
	CODE_VAR_ENV,
	CODE_SET_ENV,
	CODE_CLO_SET_ACC,
	CODE_CLO_SET_LOC,
	CODE_SET_CLO_REG,
	
	CODE_JUMP,
	CODE_BRANCH,
	CODE_PUSH,
	CODE_STACK_GROW,
	CODE_STACKFRAME,
	CODE_CALL,
	CODE_RET,
	CODE_SHIFTBACK,
	
	CODE_INFORMATION,
} codeword;
